export const HOME_SET_DEFAULT_NUMBER = 'HOME_SET_DEFAULT_NUMBER';
export const HOME_INC_CHILD_NUM = 'HOME_INC_CHILD_NUM';
export const HOME_DEC_CHILD_NUM = 'HOME_DEC_CHILD_NUM';
export const INC_ADULT_NUM = 'INC_ADULT_NUM';
export const DEC_ADULT_NUM = 'DEC_ADULT_NUM';

export const HOME_ASUG_HIDDEN_CONT = 'HOME_ASUG_HIDDEN_CONT';
export const HOME_DATE_HIDDEN_CONT = 'HOME_DATE_HIDDEN_CONT';
export const HOME_GUEST_HIDDEN_CONT = 'HOME_GUEST_HIDDEN_CONT';

export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const HOTEL_SEARCH = 'HOTEL_SEARCH'
export const HOTEL_SEARCH_FAILED = 'HOTEL_SEARCH_FAILED'
export const HOTEL_SEARCH_FORM = 'HOTEL_SEARCH_FORM'
export const HOTEL_SEARCH_FORM_COMPLETE = 'HOTEL_SEARCH_FORM_COMPLETE'
export const SET_LOADING = 'SET_LOADING'
export const HOTEL_SEARCH_FORM_FAILED = 'HOTEL_SEARCH_FORM_FAILED'
export const CHANGE_DATES = 'CHANGE_DATES'